# Generated by Django 3.2.5 on 2021-08-21 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='datarticle',
            field=models.DateField(blank=True, default=datetime.date(2021, 8, 21)),
        ),
    ]
