# Generated by Django 3.2.5 on 2021-08-21 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_datarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='datarticle',
            field=models.DateField(default=datetime.date(2021, 8, 21)),
        ),
    ]
