# Generated by Django 3.2.5 on 2021-08-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_work_todoitem', models.CharField(max_length=100)),
                ('flg_checked_todoitem', models.BooleanField(default=False)),
                ('dat_do_todoitem', models.DateField()),
                ('dat_planning_todoitem', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
